//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCRUD.vNext.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        public Labels() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebCRUD.vNext.Resources.Labels", typeof(Labels).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Add New Detail.
        /// </summary>
        public static string AddNewDetails {
            get {
                return ResourceManager.GetString("AddNewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Add new item.
        /// </summary>
        public static string AddNewItem {
            get {
                return ResourceManager.GetString("AddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to WebCRUD.vNext.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Amount.
        /// </summary>
        public static string ClaimForm_Amount {
            get {
                return ResourceManager.GetString("ClaimForm_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Claim number.
        /// </summary>
        public static string ClaimForm_ClaimNumber {
            get {
                return ResourceManager.GetString("ClaimForm_ClaimNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Date.
        /// </summary>
        public static string ClaimForm_Date {
            get {
                return ResourceManager.GetString("ClaimForm_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Event date.
        /// </summary>
        public static string ClaimForm_EventDate {
            get {
                return ResourceManager.GetString("ClaimForm_EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Event type.
        /// </summary>
        public static string ClaimForm_EventTypeCode {
            get {
                return ResourceManager.GetString("ClaimForm_EventTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Excluded.
        /// </summary>
        public static string ClaimForm_Excluded {
            get {
                return ResourceManager.GetString("ClaimForm_Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Policy.
        /// </summary>
        public static string ClaimForm_Policy {
            get {
                return ResourceManager.GetString("ClaimForm_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Price.
        /// </summary>
        public static string ClaimForm_Price {
            get {
                return ResourceManager.GetString("ClaimForm_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Product.
        /// </summary>
        public static string ClaimForm_Product {
            get {
                return ResourceManager.GetString("ClaimForm_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Qt.
        /// </summary>
        public static string ClaimForm_Qt {
            get {
                return ResourceManager.GetString("ClaimForm_Qt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Select policy.
        /// </summary>
        public static string ClaimForm_SelectPolicy {
            get {
                return ResourceManager.GetString("ClaimForm_SelectPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Service.
        /// </summary>
        public static string ClaimForm_Service {
            get {
                return ResourceManager.GetString("ClaimForm_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create claim.
        /// </summary>
        public static string ClaimsCreateForm_Title {
            get {
                return ResourceManager.GetString("ClaimsCreateForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Amounts.
        /// </summary>
        public static string ClaimSearchForm_Amounts {
            get {
                return ResourceManager.GetString("ClaimSearchForm_Amounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Approve.
        /// </summary>
        public static string ClaimSearchForm_Approve {
            get {
                return ResourceManager.GetString("ClaimSearchForm_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Claim number.
        /// </summary>
        public static string ClaimSearchForm_ClaimNumber {
            get {
                return ResourceManager.GetString("ClaimSearchForm_ClaimNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to e.g. 1234.
        /// </summary>
        public static string ClaimSearchForm_ClaimNumber_Placeholder {
            get {
                return ResourceManager.GetString("ClaimSearchForm_ClaimNumber_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Status.
        /// </summary>
        public static string ClaimSearchForm_ClaimStatus {
            get {
                return ResourceManager.GetString("ClaimSearchForm_ClaimStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Event date.
        /// </summary>
        public static string ClaimSearchForm_EventDate {
            get {
                return ResourceManager.GetString("ClaimSearchForm_EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Event date.
        /// </summary>
        public static string ClaimSearchForm_EventDateFrom {
            get {
                return ResourceManager.GetString("ClaimSearchForm_EventDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Event type.
        /// </summary>
        public static string ClaimSearchForm_EventType {
            get {
                return ResourceManager.GetString("ClaimSearchForm_EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Policy holder.
        /// </summary>
        public static string ClaimSearchForm_PolicyHolder {
            get {
                return ResourceManager.GetString("ClaimSearchForm_PolicyHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Policy holder.
        /// </summary>
        public static string ClaimSearchForm_PolicyHolderFirstName {
            get {
                return ResourceManager.GetString("ClaimSearchForm_PolicyHolderFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to e.g. Jan.
        /// </summary>
        public static string ClaimSearchForm_PolicyHolderFirstName_Placeholder {
            get {
                return ResourceManager.GetString("ClaimSearchForm_PolicyHolderFirstName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to e.g. Kowalski.
        /// </summary>
        public static string ClaimSearchForm_PolicyHolderLastName_Placeholder {
            get {
                return ResourceManager.GetString("ClaimSearchForm_PolicyHolderLastName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reject.
        /// </summary>
        public static string ClaimSearchForm_Reject {
            get {
                return ResourceManager.GetString("ClaimSearchForm_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Claim statuses.
        /// </summary>
        public static string ClaimSearchForm_SelectedStatuses {
            get {
                return ResourceManager.GetString("ClaimSearchForm_SelectedStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Search claims.
        /// </summary>
        public static string ClaimSearchForm_Title {
            get {
                return ResourceManager.GetString("ClaimSearchForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string ClaimSearchForm_TotalAmount_Hint {
            get {
                return ResourceManager.GetString("ClaimSearchForm_TotalAmount_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total Covered Amount.
        /// </summary>
        public static string ClaimSearchForm_TotalCoveredAmount_Hint {
            get {
                return ResourceManager.GetString("ClaimSearchForm_TotalCoveredAmount_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Approved.
        /// </summary>
        public static string ClaimStatus_Approved {
            get {
                return ResourceManager.GetString("ClaimStatus_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Open.
        /// </summary>
        public static string ClaimStatus_Open {
            get {
                return ResourceManager.GetString("ClaimStatus_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rejected.
        /// </summary>
        public static string ClaimStatus_Rejected {
            get {
                return ResourceManager.GetString("ClaimStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Confirm changes.
        /// </summary>
        public static string Confirm_Title {
            get {
                return ResourceManager.GetString("Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Edit claim {0}.
        /// </summary>
        public static string EditClaim_Title {
            get {
                return ResourceManager.GetString("EditClaim_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Edit order {0}.
        /// </summary>
        public static string EditOrder_Title {
            get {
                return ResourceManager.GetString("EditOrder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Accident.
        /// </summary>
        public static string EventType_Accident {
            get {
                return ResourceManager.GetString("EventType_Accident", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Birth.
        /// </summary>
        public static string EventType_Birth {
            get {
                return ResourceManager.GetString("EventType_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Death.
        /// </summary>
        public static string EventType_Death {
            get {
                return ResourceManager.GetString("EventType_Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Other.
        /// </summary>
        public static string EventType_Other {
            get {
                return ResourceManager.GetString("EventType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expired.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expires soon.
        /// </summary>
        public static string ExpiresSoon {
            get {
                return ResourceManager.GetString("ExpiresSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Open claims.
        /// </summary>
        public static string HasOpenClaims {
            get {
                return ResourceManager.GetString("HasOpenClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageSelector_Language {
            get {
                return ResourceManager.GetString("LanguageSelector_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Logged in as {0}.
        /// </summary>
        public static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Claims.
        /// </summary>
        public static string MainMenu_Claims {
            get {
                return ResourceManager.GetString("MainMenu_Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enrollment.
        /// </summary>
        public static string MainMenu_Enrollment {
            get {
                return ResourceManager.GetString("MainMenu_Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Orders.
        /// </summary>
        public static string MainMenu_Orders {
            get {
                return ResourceManager.GetString("MainMenu_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Claims.
        /// </summary>
        public static string NavHeaders_Claims {
            get {
                return ResourceManager.GetString("NavHeaders_Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No results match the specified criteria..
        /// </summary>
        public static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create order.
        /// </summary>
        public static string OrderCreateForm_Title {
            get {
                return ResourceManager.GetString("OrderCreateForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Customer.
        /// </summary>
        public static string OrderForm_Customer {
            get {
                return ResourceManager.GetString("OrderForm_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name.
        /// </summary>
        public static string OrderForm_CustomerName {
            get {
                return ResourceManager.GetString("OrderForm_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Order date.
        /// </summary>
        public static string OrderForm_Date {
            get {
                return ResourceManager.GetString("OrderForm_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Discount.
        /// </summary>
        public static string OrderForm_Discount {
            get {
                return ResourceManager.GetString("OrderForm_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Order number.
        /// </summary>
        public static string OrderForm_OrderNumber {
            get {
                return ResourceManager.GetString("OrderForm_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Price.
        /// </summary>
        public static string OrderForm_Price {
            get {
                return ResourceManager.GetString("OrderForm_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Product.
        /// </summary>
        public static string OrderForm_Product {
            get {
                return ResourceManager.GetString("OrderForm_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Quantity.
        /// </summary>
        public static string OrderForm_Quantity {
            get {
                return ResourceManager.GetString("OrderForm_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Order status.
        /// </summary>
        public static string OrderForm_Status {
            get {
                return ResourceManager.GetString("OrderForm_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total amount.
        /// </summary>
        public static string OrderForm_TotalAmount {
            get {
                return ResourceManager.GetString("OrderForm_TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total.
        /// </summary>
        public static string OrderForm_TotalAmountSum {
            get {
                return ResourceManager.GetString("OrderForm_TotalAmountSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Approve.
        /// </summary>
        public static string OrderSearchForm_Approve {
            get {
                return ResourceManager.GetString("OrderSearchForm_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Close.
        /// </summary>
        public static string OrderSearchForm_Close {
            get {
                return ResourceManager.GetString("OrderSearchForm_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Customers.
        /// </summary>
        public static string OrderSearchForm_Customers {
            get {
                return ResourceManager.GetString("OrderSearchForm_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Order date.
        /// </summary>
        public static string OrderSearchForm_OrderDate {
            get {
                return ResourceManager.GetString("OrderSearchForm_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Order date.
        /// </summary>
        public static string OrderSearchForm_OrderDateFrom {
            get {
                return ResourceManager.GetString("OrderSearchForm_OrderDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Order number.
        /// </summary>
        public static string OrderSearchForm_OrderNumber {
            get {
                return ResourceManager.GetString("OrderSearchForm_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Status.
        /// </summary>
        public static string OrderSearchForm_OrderStatus {
            get {
                return ResourceManager.GetString("OrderSearchForm_OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total amount.
        /// </summary>
        public static string OrderSearchForm_OrderTotalAmount {
            get {
                return ResourceManager.GetString("OrderSearchForm_OrderTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Products.
        /// </summary>
        public static string OrderSearchForm_Products {
            get {
                return ResourceManager.GetString("OrderSearchForm_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Search orders.
        /// </summary>
        public static string OrderSearchForm_Title {
            get {
                return ResourceManager.GetString("OrderSearchForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total amount.
        /// </summary>
        public static string OrderSearchForm_TotalAmountFrom {
            get {
                return ResourceManager.GetString("OrderSearchForm_TotalAmountFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Approved.
        /// </summary>
        public static string OrderStatus_Approved {
            get {
                return ResourceManager.GetString("OrderStatus_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Closed.
        /// </summary>
        public static string OrderStatus_Closed {
            get {
                return ResourceManager.GetString("OrderStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New.
        /// </summary>
        public static string OrderStatus_New {
            get {
                return ResourceManager.GetString("OrderStatus_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create policy.
        /// </summary>
        public static string PolicyCreateForm_Title {
            get {
                return ResourceManager.GetString("PolicyCreateForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cover from.
        /// </summary>
        public static string PolicyForm_CoverFrom {
            get {
                return ResourceManager.GetString("PolicyForm_CoverFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cover to.
        /// </summary>
        public static string PolicyForm_CoverTo {
            get {
                return ResourceManager.GetString("PolicyForm_CoverTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string PolicyForm_PolicyHolderBirthdate {
            get {
                return ResourceManager.GetString("PolicyForm_PolicyHolderBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to First name.
        /// </summary>
        public static string PolicyForm_PolicyHolderFirstName {
            get {
                return ResourceManager.GetString("PolicyForm_PolicyHolderFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tax ID.
        /// </summary>
        public static string PolicyForm_PolicyHolderIdentifier {
            get {
                return ResourceManager.GetString("PolicyForm_PolicyHolderIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Last name.
        /// </summary>
        public static string PolicyForm_PolicyHolderLastName {
            get {
                return ResourceManager.GetString("PolicyForm_PolicyHolderLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Policy number.
        /// </summary>
        public static string PolicyForm_PolicyNumber {
            get {
                return ResourceManager.GetString("PolicyForm_PolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Policy holder.
        /// </summary>
        public static string PolicySearchForm_PolicyHolder {
            get {
                return ResourceManager.GetString("PolicySearchForm_PolicyHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Search policy.
        /// </summary>
        public static string PolicySearchForm_Title {
            get {
                return ResourceManager.GetString("PolicySearchForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You are not allowed to change order status..
        /// </summary>
        public static string SecurityExceptionCannotChangeStatus {
            get {
                return ResourceManager.GetString("SecurityExceptionCannotChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You are not allowed to perform this operation..
        /// </summary>
        public static string SecurityExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("SecurityExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Use Ctrl+click to select or deselect multiple items..
        /// </summary>
        public static string SelectMultipleHint {
            get {
                return ResourceManager.GetString("SelectMultipleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sorry, unexpected error occurred while processing your request..
        /// </summary>
        public static string UnexpectedErrorDefaultMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please correct the following errors:.
        /// </summary>
        public static string ValidationErrorsDivHeader {
            get {
                return ResourceManager.GetString("ValidationErrorsDivHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The value &apos;{0}&apos; is invalid..
        /// </summary>
        public static string ValueNotValidForProperty {
            get {
                return ResourceManager.GetString("ValueNotValidForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
